### PR TITLE
Downgrade kcl to 1.9

### PR DESCRIPTION
**Pull request by mcheung610**
*Issue #, if available:*

- Add retries in bootstrap when downloading maven packages
- Downgrade KCL to 1.9

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mcheung610** [comment]
meow @josephshieh @TomGoBravo

**Comment by josephshieh** [comment]
Just curious, are we downgrading because of some compatibility issue? 
👍

**Comment by mcheung610** [comment]
Lyft does not support 2.x yet according to the streaming team.

https://lyft.slack.com/archives/C9XKK7NCQ/p1556672839090900

**Comment by mcheung610** [comment]
🚀

**Pull request merged**
